### ISSUE TITLE
 A question about building a new interprocedural analysis

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#1]
Hello every one, I'm trying to build a interprocedural analysis, but I met a problem. 
```
...
CFG of <java.math.BigInteger: int getInt(int)> is absent, try to fix this by adding option -scope=reachable
CFG of <sun.misc.Service: void access$000(java.lang.Class,java.lang.String)> is absent, try to fix this by adding option -scope=reachable

...

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "pascal.taie.analysis.graph.cfg.CFG.getEntry()" because the return value of "pascal.taie.analysis.graph.icfg.ICFGBuilder.getCFGOf(pascal.taie.language.classes.JMethod)" is null
	at pascal.taie.analysis.graph.icfg.DefaultICFG.getEntryOf(DefaultICFG.java:135)
	at pascal.taie.analysis.graph.icfg.DefaultICFG.getEntryOf(DefaultICFG.java:48)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at pascal.taie.analysis.dataflow.inter.InterSolver.initialize(InterSolver.java:64)
	at pascal.taie.analysis.dataflow.inter.InterSolver.solve(InterSolver.java:56)
	at pascal.taie.analysis.dataflow.inter.AbstractInterDataflowAnalysis.analyze(AbstractInterDataflowAnalysis.java:125)
	at pascal.taie.analysis.dataflow.inter.AbstractInterDataflowAnalysis.analyze(AbstractInterDataflowAnalysis.java:44)
	at pascal.taie.analysis.AnalysisManager.runProgramAnalysis(AnalysisManager.java:93)
	at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:71)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$0(AnalysisManager.java:60)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$1(AnalysisManager.java:59)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at pascal.taie.analysis.AnalysisManager.execute(AnalysisManager.java:59)
	at pascal.taie.Main.executePlan(Main.java:142)
	at pascal.taie.Main.lambda$main$0(Main.java:56)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:48)
	at TestTaie.main(TestTaie.java:67)

```
The log mentioned that I need to add a option `-scope=reachable`, which I did. But I encountered a new problem.

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147)
	at pascal.taie.config.AnalysisPlanner.expandPlan(AnalysisPlanner.java:149)
	at pascal.taie.Main.processConfigs(Main.java:83)
	at pascal.taie.Main.lambda$main$0(Main.java:50)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:48)
	at TestTaie.main(TestTaie.java:67)
```
Can you help me about that, thanks a lot!

**Comment by anabioticsoul** [comment]
The code is very simple, I just extended AbstractInterDataflowAnalysis and registered it in tai-e-analyses.yml, nothing else did. code shows as below:
```
public class InterTaintAnalysis extends AbstractInterDataflowAnalysis {

    // declare field ID
    public static final String ID = "intertaint";



    public InterTaintAnalysis(AnalysisConfig config) {
        super(config);
    }

    @Override
    protected boolean transferCallNode(Object o, Object o2, Object fact1) {
        return false;
    }

    @Override
    protected boolean transferNonCallNode(Object o, Object o2, Object fact1) {
        return false;
    }

    @Override
    protected Object transferNormalEdge(NormalEdge normalEdge, Object o) {
        return null;
    }

    @Override
    protected Object transferCallToReturnEdge(CallToReturnEdge callToReturnEdge, Object o) {
        return null;
    }

    @Override
    protected Object transferCallEdge(CallEdge callEdge, Object o) {
        return null;
    }

    @Override
    protected Object transferReturnEdge(ReturnEdge returnEdge, Object o) {
        return null;
    }

    @Override
    public boolean isForward() {
        return false;
    }

    @Override
    public Object newBoundaryFact(Object o) {
        return null;
    }

    @Override
    public Object newInitialFact() {
        return null;
    }

    @Override
    public void meetInto(Object o, Object fact1) {
    }
}
```

**Comment by silverbullettt** [comment]
Hi @anabioticsoul, it looks like an issue in config system. I've made a change and could you please check if it fix your problem?

**Comment by anabioticsoul** [comment]
> Hi @anabioticsoul, it looks like an issue in config system. I've made a change and could you please check if it fix your problem?

Yes, it works! Thank you very much!
