### ISSUE TITLE
Cannot find option 'taint-config-providers', please check your configuration and option key

### ISSUE THREAD

**Issue by YunFy26** [pascal-lab/Tai-e#122]
### 📝 Overall Description

Hello, I developed a program using tai-e as a dependency. I packaged the program into a jar, I specified the path of `options.yml` using the parameter, but when run it as a jar package, throw exception as follows
```java
$ java -jar WebAnalyzer-all.jar --options-file=./options.yml
Tai-e starts ...
Output directory: /Users/yuntsy/Desktop/demo/output
Writing options to /Users/yuntsy/Desktop/demo/output/options.yml
Writing log to /Users/yuntsy/Desktop/demo/output/tai-e.log
java.version: 17.0.11
java.version.date: 2024-04-16
java.runtime.version: 17.0.11+7-LTS-207
java.vendor: Oracle Corporation
java.vendor.version: null
os.name: Mac OS X
os.version: 15.0
os.arch: aarch64
Tai-e Version: 0.5.1-SNAPSHOT
Manifest does not contain Tai-e commit information
Tai-e Commit: Unknown
Writing analysis plan to /Users/yuntsy/Desktop/demo/output/tai-e-plan.yml
WorldBuilder starts ...
Scanning /Users/yuntsy/My/Projects/Java/WebAnalyzer/WebGoat/BOOT-INF/classes ... 284 classes
Warning: main class was not given!
10778 classes with 102972 methods in the world
WorldBuilder finishes, elapsed time: 2.54s
routerAnalysis starts ...
routerAnalysis finishes, elapsed time: 0.00s
beanAnalysis starts ...
beanAnalysis finishes, elapsed time: 0.00s
pta starts ...
Exception in thread "main" pascal.taie.config.ConfigException: Cannot find option 'taint-config-providers', please check your configuration and option key
	at pascal.taie.config.AnalysisOptions.get(AnalysisOptions.java:99)
	at pascal.taie.analysis.pta.PointerAnalysis.setPlugin(PointerAnalysis.java:155)
	at pascal.taie.analysis.pta.PointerAnalysis.runAnalysis(PointerAnalysis.java:118)
	at pascal.taie.analysis.pta.PointerAnalysis.analyze(PointerAnalysis.java:107)
	at pascal.taie.analysis.pta.PointerAnalysis.analyze(PointerAnalysis.java:64)
	at pascal.taie.analysis.AnalysisManager.runProgramAnalysis(AnalysisManager.java:148)
	at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:135)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$0(AnalysisManager.java:104)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$1(AnalysisManager.java:103)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at pascal.taie.analysis.AnalysisManager.execute(AnalysisManager.java:102)
	at pascal.taie.Main.executePlan(Main.java:154)
	at pascal.taie.Main.lambda$main$0(Main.java:62)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:52)
	at org.example.MyMain.main(MyMain.java:38)
```

### 🎯 Expected Behavior

None

### 🐛 Current Behavior

None

### ⚙️ Tai-e Arguments

<details>
  <summary>🔍 Click here to see Tai-e Options</summary>
  

  ```yaml
optionsFile: null
printHelp: false
classPath:
- ../../My/Projects/Java/WebAnalyzer/WebGoat/BOOT-INF/lib
appClassPath:
- ../../My/Projects/Java/WebAnalyzer/WebGoat/BOOT-INF/classes
mainClass: null
inputClasses: []
javaVersion: 17
prependJVM: true
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: false
scope: REACHABLE
nativeModel: true
planFile: null
analyses:
  ir-dumper: ;
  routerAnalysis: ""
  beanAnalysis: ""
  cg: ""
  cfg: ""
  pta: "plugins:[org.example.spring.DICGConstructorPlugin]"
onlyGenPlan: false
keepResult:
- $KEEP-ALL

  ```
</details>
<details>
  <summary>🔍 Click here to see Tai-e Analysis Plan</summary>
  

  ```yaml
  {{The content of 'output/tai-e-plan.yml' file}}
  ```
</details>

### 📜 Tai-e Log

<details>
  <summary>🔍 Click here to see Tai-e Log</summary>
  

  ```
  {{The content of 'output/tai-e.log' file}}
  ```
</details>

### ℹ️ Additional Information

`build.gradle.kts`
```
plugins {
    java
    application
    id("com.github.johnrengelman.shadow") version "8.1.0"  
}

repositories {
    mavenCentral()
    maven { url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/") }
}

group = "org.example"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

application {
    mainClass.set("org.example.MyMain")
}

val taieVersion = "0.5.1-SNAPSHOT" 

tasks {
    jar {
        manifest {
            attributes(
                "Main-Class" to "org.example.MyMain", 
                "Tai-e-Version" to taieVersion,
            )
        }
    }
}
dependencies {
    implementation("net.pascal-lab:tai-e:$taieVersion")
    implementation("org.apache.logging.log4j:log4j-api:2.23.0")
    implementation("org.apache.logging.log4j:log4j-core:2.23.0")
    implementation("commons-cli:commons-cli:1.4")


    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.0")


}
```

**Comment by zhangt2333** [comment]
Tai-e have updated and release the SNAPSHOT version today.

You need to update your `src/main/resources/tai-e-analyses.yml` if you overrided it:

https://github.com/pascal-lab/Tai-e/commit/d34aa5032e6d77d2d86c727e483f73c29ad55966#diff-39c383a5c8fffc7a1d28ae7e84784205d2ef9030bd19933663b86969105d5246R29-R31

```diff
-    taint-config: null # path to config file of taint analysis,
-    # when this file is given, taint analysis will be enabled
+    taint-config: null # path (of dir/file) to config file of taint analysis,
+    taint-config-providers: [ ] # class names of taint config provider classes
+    # when this path/provider is given, taint analysis will be enabled
```

**Comment by YunFy26** [comment]
Got it. Thanks! Now, it can be successfully executed！
