### ISSUE TITLE
[Question] 1obj pointer analysis failed due to OOM in laptop

### ISSUE THREAD

**Issue by enochii** [pascal-lab/Tai-e#14]
Hello, thanks for the great framework. I have a question about the Tai-e memory consumption.

### Description

In my laptop, I run pointer analysis with `1obj` for `antlr`, it failed due to OOM(Out of Memory). My laptop has 32GB memory, I also change the `Help|Change Memory Setting` of `Intellij idea` to 32GB. Though I observe that the `idea` memory showed in `Windows Task Manager` is not high(around 4GB).

To my limited knowledge, the memory consumption would not be too high for a `1obj` pointer analysis to analyze a small benchmark like `antlr`.  Here is the error message:

```shell
Using reflection log from java-benchmarks\dacapo-2006\antlr-refl.log

Java heap space
java.lang.OutOfMemoryError: Java heap space
	at pascal.taie.util.collection.AbstractHybridSet.iterator(AbstractHybridSet.java:241)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:335)
	at pascal.taie.util.collection.GenericBitSet.addAll(GenericBitSet.java:103)
	at pascal.taie.util.collection.AbstractHybridSet.addAll(AbstractHybridSet.java:181)
	at pascal.taie.analysis.pta.pts.DelegatePointsToSet.addAll(DelegatePointsToSet.java:51)
	at pascal.taie.analysis.pta.core.solver.WorkList.addEntry(WorkList.java:55)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.addPointsTo(DefaultSolver.java:654)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.lambda$propagate$0(DefaultSolver.java:273)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver$$Lambda$329/0x0000000800f35718.accept(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.propagate(DefaultSolver.java:272)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.analyze(DefaultSolver.java:248)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.solve(DefaultSolver.java:222)
	at pascal.taie.analysis.pta.PointerAnalysis.runAnalysis(PointerAnalysis.java:118)
	at pascal.taie.analysis.pta.PointerAnalysis.analyze(PointerAnalysis.java:106)
	at pascal.taie.analysis.pta.PointerAnalysis.analyze(PointerAnalysis.java:63)
	at pascal.taie.analysis.AnalysisManager.runProgramAnalysis(AnalysisManager.java:93)
	at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:71)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$0(AnalysisManager.java:60)
	at pascal.taie.analysis.AnalysisManager$$Lambda$233/0x0000000800eeb8b8.run(Unknown Source)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer$$Lambda$117/0x0000000800dbfda8.get(Unknown Source)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$1(AnalysisManager.java:59)
	at pascal.taie.analysis.AnalysisManager$$Lambda$232/0x0000000800eeb698.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at pascal.taie.analysis.AnalysisManager.execute(AnalysisManager.java:59)
	at pascal.taie.Main.executePlan(Main.java:142)
	at pascal.taie.Main.lambda$main$0(Main.java:56)
```

### tai-e arguments

```java
  DaCapoRunner.main(new String[]{"1-obj", "antlr"});
```

### Runtime environment

- Windows 10
- openjdk18.0.2

### Question

Noticing Tai-e technical report requires a 128-GB-setting, I wonder If there is any way to make `1obj` pointer analysis run normally in the laptop? e.g., turn off some options at the cost of precision loss. 

Thanks for your time!

**Comment by enochii** [comment]
### Update

It may be related to Junit. I have the below code. Using `DaCapoTest.main` to call `DacapoRunner.main` works well, but this is not the case with Junit test(OOM error) even with same arguments.

```java
public class DaCapoTest {
    final static String ANTLR = "antlr";
    public static void main(String[] args) {
        DaCapoRunner.main(new String[]{"1-obj", ANTLR});
    }
    @Test
    public void SimpleTest() {
        DaCapoRunner.main(new String[]{"1-obj", ANTLR});
    }
}
```

**Comment by zhangt2333** [comment]
When using Gradle for JUnit testing, the test process is essentially a Gradle worker whose heap size is configured [here](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcessBuilder.java#L236-L238).

You can now modify it in `build.gradle.kts`:

https://github.com/pascal-lab/Tai-e/blob/9e70bfbd26253f90bc8ede75183687e2f1d300ab/build.gradle.kts#L51-L55
