### ISSUE TITLE
Feature request: Dominator algorithm for control flow analysis

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#15]
Hello everyone, I want to obtain the jump scope such as the two control flows of `if` statement. Consider an example:
if (condition1) 
`{
interested statements
}`
else
`{
interested statements
}`

The methods provided by `Tai-e` only indicate the target statement without the exit statement of control flow. Could you please help me with that, thank you very much!

**Comment by zhangt2333** [comment]
See [Dominator](https://en.wikipedia.org/wiki/Dominator_(graph_theory)) introduced by https://github.com/pascal-lab/Tai-e/commit/2b03f039bb775faab27288c4d32067e0135cd0e5.

**Comment by anabioticsoul** [comment]
Really helpful, thank you so much!

**Comment by anabioticsoul** [comment]
Sorry to bother you again, I met an infinite loop when instantiating the dominatorFinder.
```
DominatorFinder<Stmt> dominatorFinder = new DominatorFinder<>(icfg);
```

**Comment by zhangt2333** [comment]
It seems that there is a bug in `pascal.taie.util.graph.DominatorFinder#findDominators`.

Could you provide the graph you passed to `DominatorFinder` for bug reproduction?


You could dump your graph by adding and calling the following method in `pascal.taie.util.graph.Graph`:

```Java
default void dump() {
    Map<N, Integer> indexer = Maps.newMap();

    int index = 1;
    for (N node : getNodes()) {
        indexer.put(node, index++);
    }

    // dump Graph to file
    try (FileWriter writer = new FileWriter("graph.txt")) {
        for (N node : getNodes()) {
            Integer from = indexer.get(node);
            for (Edge<N> edge : this.getOutEdgesOf(node)) {
                Integer to = indexer.get(edge.getTarget());
                writer.write(from + "->" + to + "\n");
            }
        }
    } catch (Throwable t) {
        throw new RuntimeException(t);
    }
}

```

**Comment by anabioticsoul** [comment]
[graph.txt](https://github.com/pascal-lab/Tai-e/files/10186826/graph.txt)

**Comment by zhangt2333** [comment]
There is no bug in `pascal.taie.util.graph.DominatorFinder#findDominators`. I ran the results out using 20G of memory:

<img width="2045" alt="image" src="https://user-images.githubusercontent.com/35210901/206620751-899bae92-16c0-4d65-8c12-25a2e411d120.png">

I found most values (`pascal.taie.util.collection.IndexerBitSet`) of the map (`pascal.taie.util.graph.DominatorFinder#node2Doms`) is sparse, it may be that the graph is too sparse and program consumes a lot of memory on BitSet.

**Comment by anabioticsoul** [comment]
Thank you so much, I really appreciate it! I temporarily try to reduce the number of input files to escape it. 
I met a new problem when I ran the program in a server with **Ubuntu 20.04**, it finally threw `RuntimeException`. But the same environment works well in **Windows 11**.
``` ASN.1
Exception in thread "main" java.lang.RuntimeException: Failed to convert <org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl: org.apache.hadoop.yarn.api.protocolrecords.RegisterApplicationMasterResponse registerApplicationMaster()>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2250)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:446)
	at soot.jimple.toolkits.annotation.LineNumberAdder.internalTransform(LineNumberAdder.java:61)
	at soot.PackManager.runPacksNormally(PackManager.java:496)
	at soot.PackManager.runPacks(PackManager.java:425)
	at soot.Main.run(Main.java:280)
	at pascal.taie.frontend.soot.SootWorldBuilder.runSoot(SootWorldBuilder.java:254)
	at pascal.taie.frontend.soot.SootWorldBuilder.build(SootWorldBuilder.java:85)
	at pascal.taie.Main.lambda$buildWorld$3(Main.java:121)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.buildWorld(Main.java:116)
	at pascal.taie.Main.lambda$main$0(Main.java:55)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:48)
	at main.TaieMain.main(TaieMain.java:28)
Caused by: java.lang.RuntimeException: Trying to create interface invoke expression for non-interface type: org.apache.hadoop.yarn.api.ApplicationMasterProtocol Use JVirtualInvokeExpr or JSpecialInvokeExpr instead!
	at soot.jimple.internal.JInterfaceInvokeExpr.<init>(JInterfaceInvokeExpr.java:47)
	at soot.jimple.Jimple.newInterfaceInvokeExpr(Jimple.java:491)
	at soot.asm.AsmMethodSource.convertMethodInsn(AsmMethodSource.java:1437)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1966)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2248)
	... 20 more
```
It seems to occur in the initialization phase of analysis.

**Comment by zhangt2333** [comment]
I made some amazing optimization for `pascal.taie.util.graph.DominatorFinder#findDominators`.

Before optimization:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/35210901/206711660-75932e96-3c8a-4479-b0f6-090612c0482b.png">

After optimization:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/35210901/206711682-c85cc04d-38f4-40df-a687-ff63b2b33d7b.png">

We will push a commit on the default branch some time later.

You can look ahead at this change and use it before we push: https://github.com/pascal-lab/Tai-e/commit/605bedeb267555dae213e536b09d5d7180e9d0b7

**Comment by zhangt2333** [comment]
> Thank you so much, I really appreciate it! I temporarily try to reduce the number of input files to escape it. I met a new problem when I ran the program in a server with **Ubuntu 20.04**, it finally threw `RuntimeException`. But the same environment works well in **Windows 11**.

This problem should be discussed in another new issue.

**Comment by zhangt2333** [comment]
> I made some amazing optimization for `pascal.taie.util.graph.DominatorFinder#findDominators`: [7b7b7e5](https://github.com/pascal-lab/Tai-e/commit/7b7b7e576f279f28a78e16b75ef7b03ee0ebfc48)
> 
> Before optimization: <img alt="image" width="500" src="https://user-images.githubusercontent.com/35210901/206711660-75932e96-3c8a-4479-b0f6-090612c0482b.png">
> 
> After optimization: <img alt="image" width="500" src="https://user-images.githubusercontent.com/35210901/206711682-c85cc04d-38f4-40df-a687-ff63b2b33d7b.png">

Try https://github.com/pascal-lab/Tai-e/commit/7b7b7e576f279f28a78e16b75ef7b03ee0ebfc48.

**Comment by anabioticsoul** [comment]
OK, I will try it. Thank you so much!

**Comment by anabioticsoul** [comment]
It seems some dominated statements are incorrect. Here is an example, I try to get the dominated statements of ` if $r1 != $r3 goto label1;`. 
``` java
       private java.util.List getAuthMethods(org.apache.hadoop.security.token.SecretManager, org.apache.hadoop.conf.Configuration)
    {
        java.util.ArrayList $r2;
        org.apache.hadoop.security.SaslRpcServer$AuthMethod $r12, $r20;
        org.apache.hadoop.conf.Configuration r0;
        java.lang.String $r10, $r18, $r25;
        org.apache.hadoop.ipc.Server r19;
        org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod $r1, $r3, $r7, $r11, $r15;
        org.slf4j.Logger $r6, $r21;
        java.lang.IllegalArgumentException $r13;
        org.apache.hadoop.security.token.SecretManager r4;
        java.lang.StringBuilder $r5, $r8, $r9, $r14, $r16, $r17, $r22, $r23, $r24;

        r19 := @this: org.apache.hadoop.ipc.Server;

        r4 := @parameter0: org.apache.hadoop.security.token.SecretManager;

        r0 := @parameter1: org.apache.hadoop.conf.Configuration;

        $r1 = staticinvoke <org.apache.hadoop.security.SecurityUtil: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod getAuthenticationMethod(org.apache.hadoop.conf.Configuration)>(r0);

        $r2 = new java.util.ArrayList;

        specialinvoke $r2.<java.util.ArrayList: void <init>()>();

        $r3 = <org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod TOKEN>;

        if $r1 != $r3 goto label1;

        if r4 != null goto label2;

        $r13 = new java.lang.IllegalArgumentException;

        $r14 = new java.lang.StringBuilder;

        specialinvoke $r14.<java.lang.StringBuilder: void <init>()>();

        $r15 = <org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod TOKEN>;

        $r16 = virtualinvoke $r14.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r15);

        $r17 = virtualinvoke $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" authentication requires a secret manager");

        $r18 = virtualinvoke $r17.<java.lang.StringBuilder: java.lang.String toString()>();

        specialinvoke $r13.<java.lang.IllegalArgumentException: void <init>(java.lang.String)>($r18);

        throw $r13;

     label1:
        if r4 == null goto label2;

        $r6 = <org.apache.hadoop.ipc.Server: org.slf4j.Logger LOG>;

        $r5 = new java.lang.StringBuilder;

        specialinvoke $r5.<java.lang.StringBuilder: void <init>()>();

        $r7 = <org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod TOKEN>;

        $r8 = virtualinvoke $r5.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r7);

        $r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" authentication enabled for secret manager");

        $r10 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.String toString()>();

        interfaceinvoke $r6.<org.slf4j.Logger: void debug(java.lang.String)>($r10);

        $r11 = <org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod TOKEN>;

        $r12 = virtualinvoke $r11.<org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.SaslRpcServer$AuthMethod getAuthMethod()>();

        interfaceinvoke $r2.<java.util.List: boolean add(java.lang.Object)>($r12);

     label2:
        $r20 = virtualinvoke $r1.<org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.SaslRpcServer$AuthMethod getAuthMethod()>();

        interfaceinvoke $r2.<java.util.List: boolean add(java.lang.Object)>($r20);

        $r21 = <org.apache.hadoop.ipc.Server: org.slf4j.Logger LOG>;

        $r22 = new java.lang.StringBuilder;

        specialinvoke $r22.<java.lang.StringBuilder: void <init>()>();

        $r23 = virtualinvoke $r22.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Server accepts auth methods:");

        $r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r2);

        $r25 = virtualinvoke $r24.<java.lang.StringBuilder: java.lang.String toString()>();

        interfaceinvoke $r21.<org.slf4j.Logger: void debug(java.lang.String)>($r25);

        return $r2;
    }
```
But the result contains 248 statements, some of which are not in the same method as the target. 
![image](https://user-images.githubusercontent.com/29519209/207295732-8f4c4dd7-6dc9-4125-8ec3-4af6c2a546b2.png)

**Comment by zhangt2333** [comment]
Could you explain the incompletion of result in your above case clearly, e.g., what is expexted and what is actual, which results are the extra ones, what is the result you filtered?   :)

Besides, it seems that the IR in your case is in Jimple format (`.jimple`), but not Tai-e IR format (`.tir`). If you do not know how to dump IR in `.tir` format, just append the argument `-a class-dumper` to activate [it](https://github.com/pascal-lab/Tai-e/blob/master/src/main/java/pascal/taie/analysis/misc/ClassDumper.java).
```
        r19 := @this: org.apache.hadoop.ipc.Server;

        r4 := @parameter0: org.apache.hadoop.security.token.SecretManager;

        r0 := @parameter1: org.apache.hadoop.conf.Configuration;
```

**Comment by anabioticsoul** [comment]
> Besides, it seems that the IR in your case is in Jimple format (`.jimple`), but not in Tai-e IR format (`.tir`). If you do not know how to dump IR in `.tir` format, just append the argument `-a class-dumper` to activate [it](https://github.com/pascal-lab/Tai-e/blob/master/src/main/java/pascal/taie/analysis/misc/ClassDumper.java).

The stack trace hints that it lacks the argument `dump-dir`. So how to config it?
```
Exception in thread "main" pascal.taie.util.AnalysisException: Failed to initialize pascal.taie.analysis.misc.ClassDumper
	at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:88)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$0(AnalysisManager.java:60)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$1(AnalysisManager.java:59)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at pascal.taie.analysis.AnalysisManager.execute(AnalysisManager.java:59)
	at pascal.taie.Main.executePlan(Main.java:142)
	at pascal.taie.Main.lambda$main$0(Main.java:56)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:48)
	at main.TaieMain.main(TaieMain.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:68)
	... 16 more
Caused by: pascal.taie.config.ConfigException: Cannot find option 'dump-dir', please check your configuration and option key
	at pascal.taie.config.AnalysisOptions.get(AnalysisOptions.java:91)
	at pascal.taie.config.AnalysisOptions.getString(AnalysisOptions.java:98)
	at pascal.taie.analysis.misc.ClassDumper.<init>(ClassDumper.java:73)
	... 22 more

```

**Comment by zhangt2333** [comment]
> The stack trace hints that it lacks the argument `dump-dir`. So how to config it?

`-a class-dumper= dump-dir:./output`

**Comment by anabioticsoul** [comment]
> `-a class-dumper= dump-dir:./output` (according to [this](https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options)#analyses--a---analysis--a-idkeyvalue))

I append it as you say but results in `UnsupportedOperationException`.
```
Tai-e starts ...
Writing options to output\options.yml
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractMap.put(AbstractMap.java:209)
	at java.base/java.util.AbstractMap.putAll(AbstractMap.java:281)
	at pascal.taie.config.AnalysisOptions.update(AnalysisOptions.java:74)
	at pascal.taie.config.ConfigManager.lambda$overwriteOptions$0(ConfigManager.java:85)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at pascal.taie.config.ConfigManager.overwriteOptions(ConfigManager.java:83)
	at pascal.taie.Main.processConfigs(Main.java:82)
	at pascal.taie.Main.lambda$main$0(Main.java:50)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:48)
	at main.TaieMain.main(TaieMain.java:28)
```

**Comment by zhangt2333** [comment]
I passed the argument in the following way, what about you?

<img width="1830" alt="image" src="https://user-images.githubusercontent.com/35210901/207356911-a8cd1d08-137c-4adf-8961-d7c8bc014f15.png">

**Comment by anabioticsoul** [comment]
That's strange, I use the same way to handle arguments.
![image](https://user-images.githubusercontent.com/29519209/207359396-472fcc14-991e-429b-89ad-2850ead442b6.png)

**Comment by zhangt2333** [comment]
Could you run it successfully?
```
        Main.main(new String[]{
                "-pp",
                "-cp", "src/test/resources/pta/basic",
                "-m", "New",
                "-a", "pta=implicit-entries:false;action:compare;action-file:src/test/resources/pta/basic/New-pta-expected.txt;only-app:true",
                "-a", "class-dumper",
        });
```

**Comment by zhangt2333** [comment]
I can also run the `tai-e-all.jar` in command line successfully. 

```
"C:\Program Files\Java\jdk-17.0.1+12\bin\java.exe" -jar build\tai-e-all.jar -pp -cp src/test/resources/pta/basic -m "New" -a pta=implicit-entries:false;action:compare;action-file:src/test/resources/pta/basic/New-pta-expected.txt;only-app:true -a class-dumper
```

![image](https://user-images.githubusercontent.com/35210901/207371637-5c95134a-515c-4c5a-992e-86650b88551b.png)

**Comment by anabioticsoul** [comment]
I don't find out where the problem is, but I finally resolve it by modifying `ClassDumper`.
```
public ClassDumper(AnalysisConfig config) {
        super(config);
        String path = null;
        try{
            path = getOptions().getString("dump-dir");
        }catch(ConfigException | AnalysisException e){
            logger.warn("Failed to get dump-dir", e);
        }
        dumpDir = path != null ? new File(path) : Configs.getOutputDir();
        if (!dumpDir.exists()) {
            dumpDir.mkdirs();
        }
        try {
            logger.info("Dump directory: {}", dumpDir.getCanonicalPath());
        } catch (IOException e) { // would this happen after dumpDir.mkdirs()?
            logger.warn("Failed to get canonical path of dump-dir", e);
            logger.info("Dump directory: {}", dumpDir.getAbsolutePath());
        }
    }

```

**Comment by anabioticsoul** [comment]
I think the indexes results of the method `getNodesDominatedBy()` towards statement `[4@L3080] if ($r1 != $r3) goto 16;` should be from 4 to 39, but they are from 4 to27 actually and with about more than 200 unrelated statements.
``` java
private java.util.List getAuthMethods(org.apache.hadoop.security.token.SecretManager secretManager, org.apache.hadoop.conf.Configuration conf) {
        org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod $r1, $r3, $r15, $r7, $r11;
        java.util.ArrayList $r2;
        null-type %nullconst;
        java.lang.IllegalArgumentException $r13;
        java.lang.StringBuilder $r14, $r16, $r17, $r5, $r8, $r9, $r22, $r23, $r24;
        java.lang.String %stringconst0, $r18, %stringconst1, $r10, %stringconst2, $r25;
        org.slf4j.Logger $r6, $r21;
        org.apache.hadoop.security.SaslRpcServer$AuthMethod $r12, $r20;
        [0@L3077] $r1 = invokestatic <org.apache.hadoop.security.SecurityUtil: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod getAuthenticationMethod(org.apache.hadoop.conf.Configuration)>(conf);
        [1@L3079] $r2 = new java.util.ArrayList;
        [2@L3079] invokespecial $r2.<java.util.ArrayList: void <init>()>();
        [3@L3080] $r3 = <org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod TOKEN>;
        [4@L3080] if ($r1 != $r3) goto 16;
        [5@L3081] if (secretManager != %nullconst) goto 29;
        [6@L3082] $r13 = new java.lang.IllegalArgumentException;
        [7@L3082] $r14 = new java.lang.StringBuilder;
        [8@L3082] invokespecial $r14.<java.lang.StringBuilder: void <init>()>();
        [9@L3082] $r15 = <org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod TOKEN>;
        [10@L3082] $r16 = invokevirtual $r14.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r15);
        [11@L3082] %stringconst0 = " authentication requires a secret manager";
        [12@L3082] $r17 = invokevirtual $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(%stringconst0);
        [13@L3082] $r18 = invokevirtual $r17.<java.lang.StringBuilder: java.lang.String toString()>();
        [14@L3082] invokespecial $r13.<java.lang.IllegalArgumentException: void <init>(java.lang.String)>($r18);
        [15@L3082] throw $r13;
        [16@L3085] if (secretManager == %nullconst) goto 29;
        [17@L3086] $r6 = <org.apache.hadoop.ipc.Server: org.slf4j.Logger LOG>;
        [18@L3086] $r5 = new java.lang.StringBuilder;
        [19@L3086] invokespecial $r5.<java.lang.StringBuilder: void <init>()>();
        [20@L3086] $r7 = <org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod TOKEN>;
        [21@L3086] $r8 = invokevirtual $r5.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r7);
        [22@L3086] %stringconst1 = " authentication enabled for secret manager";
        [23@L3086] $r9 = invokevirtual $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(%stringconst1);
        [24@L3086] $r10 = invokevirtual $r9.<java.lang.StringBuilder: java.lang.String toString()>();
        [25@L3086] invokeinterface $r6.<org.slf4j.Logger: void debug(java.lang.String)>($r10);
        [26@L3089] $r11 = <org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod TOKEN>;
        [27@L3089] $r12 = invokevirtual $r11.<org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.SaslRpcServer$AuthMethod getAuthMethod()>();
        [28@L3089] invokeinterface $r2.<java.util.List: boolean add(java.lang.Object)>($r12);
        [29@L3091] $r20 = invokevirtual $r1.<org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.SaslRpcServer$AuthMethod getAuthMethod()>();
        [30@L3091] invokeinterface $r2.<java.util.List: boolean add(java.lang.Object)>($r20);
        [31@L3093] $r21 = <org.apache.hadoop.ipc.Server: org.slf4j.Logger LOG>;
        [32@L3093] $r22 = new java.lang.StringBuilder;
        [33@L3093] invokespecial $r22.<java.lang.StringBuilder: void <init>()>();
        [34@L3093] %stringconst2 = "Server accepts auth methods:";
        [35@L3093] $r23 = invokevirtual $r22.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(%stringconst2);
        [36@L3093] $r24 = invokevirtual $r23.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r2);
        [37@L3093] $r25 = invokevirtual $r24.<java.lang.StringBuilder: java.lang.String toString()>();
        [38@L3093] invokeinterface $r21.<org.slf4j.Logger: void debug(java.lang.String)>($r25);
        [39@L3094] return $r2;
    }

```

**Comment by zhangt2333** [comment]
Could you dump and provide the necessary information to help issue reproduction? 

If so, you can add and call following code in `pascal.taie.analysis.graph.icfg.ICFG`:
```Java
    default void dump() {
        Map<Node, Integer> indexer = Maps.newMap();

        int index = 1;
        for (Node node : getNodes()) {
            indexer.put(node, index++);
        }

        // dump Graph nodes to file
        try (FileWriter writer = new FileWriter("graph-nodes.txt")) {
            for (Node node : getNodes()) {
                Integer id = indexer.get(node);
                if (node instanceof Stmt stmt
                        && getContainingMethodOf(node) instanceof JMethod container) {
                    writer.write(id + "\t" + container.getSignature()
                            + "\t" + IRPrinter.toString(stmt) + "\n");
                }
            }
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }

        // dump Graph to file
        try (FileWriter writer = new FileWriter("graph.txt")) {
            for (Node node : getNodes()) {
                Integer from = indexer.get(node);
                for (Edge<Node> edge : this.getOutEdgesOf(node)) {
                    Integer to = indexer.get(edge.getTarget());
                    writer.write(from + "->" + to + "\n");
                }
            }
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }
```

**Comment by anabioticsoul** [comment]
[graph-nodes.zip](https://github.com/pascal-lab/Tai-e/files/10224377/graph-nodes.zip)

**Comment by zhangt2333** [comment]
> I think the indexes of the result `getNodesDominatedBy()` towards the statement `[4@L3080] if ($r1 != $r3) goto 16;` should be from 4 to 39, but they are from 4 to27 actually with about more than 200 unrelated statements.

Are you sure to run Dominator on **ICFG** but not **CFG** for your sake? 

Look at your case:
```java
[27@L3089] $r12 = invokevirtual $r11.<org.apache.hadoop.security.UserGroupInformation$AuthenticationMethod: org.apache.hadoop.security.SaslRpcServer$AuthMethod getAuthMethod()>();
[28@L3089] invokeinterface $r2.<java.util.List: boolean add(java.lang.Object)>($r12);
```
The control flow `[27@L3089] -> [28@L3089]` don't exists in **ICFG**, but `[27@L3089] -> [The Entry Statement of Method 'getAuthMethod()'] -> ... -> [The Exit Statement of Method 'getAuthMethod()'] -> [28@L3089]` exists.

It **may** causes the statement `[28@L3089]` isn't dominated by `[27@L3089]` or `[4@L3080]` (ditto).

Besides, our implementation of Dominator cannot be directly used in ICFG (CFG is ok).  So, are you sure to run Dominator on **ICFG** but not **CFG** for your sake?

**Comment by anabioticsoul** [comment]
> Besides, our implementation of Dominator cannot be directly used in ICFG (CFG is ok). So, are you sure to run Dominator on ICFG but not CFG for your sake?

Yes, you are right. I have confused the results of the dominator of ICFG and CFG. I thought they were the same. That solves my question, thank you so much!

**Comment by anabioticsoul** [comment]
> I append it as you say but results in `UnsupportedOperationException`.
> 
> ```
> Tai-e starts ...
> Writing options to output\options.yml
> Exception in thread "main" java.lang.UnsupportedOperationException
> ```

I found that I have used an old version of the file `tai-e-analyses.yml` which didn't support the option `dump-dir`.

**Comment by zhangt2333** [comment]
> I found that I have used an old version of the file `tai-e-analyses.yml` which didn't support the option `dump-dir`.

Besides, in https://github.com/pascal-lab/Tai-e/commit/dce15b7c2f95c73853ba1477777df47aae7645d5, the `ClassDumper` is renamed to `IRDumper` and the Analysis Id `class-dumper` is renamed to `ir-dumper`.

Maybe you need to change 
> "-a", "class-dumper"

to 

> "-a", "ir-dumper"

in latest Tai-e.

**Comment by anabioticsoul** [comment]
OK, thanks!
