### ISSUE TITLE
ArrayIndexOutOfBoundsException occurred during interprocedural constant propagation

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#2]
Hello everyone! I've met a problem when I used interprocedural constant propagation. The console log is as follows:
```
inter-constprop starts ...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680)
	at pascal.taie.analysis.dataflow.inter.InterConstantPropagation.transferCallEdge(InterConstantPropagation.java:336)
	at pascal.taie.analysis.dataflow.inter.InterConstantPropagation.transferCallEdge(InterConstantPropagation.java:59)
	at pascal.taie.analysis.dataflow.inter.AbstractInterDataflowAnalysis.transferEdge(AbstractInterDataflowAnalysis.java:104)
	at pascal.taie.analysis.dataflow.inter.InterSolver.lambda$doSolve$2(InterSolver.java:87)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at pascal.taie.analysis.dataflow.inter.InterSolver.doSolve(InterSolver.java:85)
	at pascal.taie.analysis.dataflow.inter.InterSolver.solve(InterSolver.java:57)
	at pascal.taie.analysis.dataflow.inter.AbstractInterDataflowAnalysis.analyze(AbstractInterDataflowAnalysis.java:125)
	at pascal.taie.analysis.dataflow.inter.AbstractInterDataflowAnalysis.analyze(AbstractInterDataflowAnalysis.java:44)
	at pascal.taie.analysis.AnalysisManager.runProgramAnalysis(AnalysisManager.java:93)
	at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:71)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$0(AnalysisManager.java:60)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$1(AnalysisManager.java:59)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at pascal.taie.analysis.AnalysisManager.execute(AnalysisManager.java:59)
	at pascal.taie.Main.executePlan(Main.java:142)
	at pascal.taie.Main.lambda$main$0(Main.java:56)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:48)
	at TestTaie.main(TestTaie.java:70)
```
It seems that the arguments does not match the parameters. The debug information is as follows:
![image](https://user-images.githubusercontent.com/29519209/183283948-7825ab23-eeb1-4011-9b3d-47c19db40a71.png)

Could you please help me about that, thanks a lot!

**Comment by zhangt2333** [comment]
It seems that this commit https://github.com/pascal-lab/Tai-e/commit/e4ee97793115c0769eeef36866dcae351322e479 fixes your issue.

Are you running on the latest Tai-e? If not, a step to reproduce your problem is required to be provided.

**Comment by anabioticsoul** [comment]
> It seems that this commit [e4ee977](https://github.com/pascal-lab/Tai-e/commit/e4ee97793115c0769eeef36866dcae351322e479) fixes your issue.
> 
> Are you running on the latest Tai-e? If not, a step to reproduce your problem is required to be provided.

Yes, you are right! After updating Tai-e, the program goes well. Thank you very much!
