### ISSUE TITLE
NPE in `ClassHierarchyImpl.isSubclass` because "superclass" is null

### ISSUE THREAD

**Issue by PeteLing** [pascal-lab/Tai-e#39]
### Describe the bug

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "superclass" is null
	at pascal.taie.language.classes.ClassHierarchyImpl.isSubclass(ClassHierarchyImpl.java:398)
	at pascal.taie.language.type.TypeSystemImpl.isSubtype(TypeSystemImpl.java:183)
	at pascal.taie.analysis.pta.core.solver.TypeFilter.lambda$apply$0(TypeFilter.java:56)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at pascal.taie.analysis.pta.core.solver.TypeFilter.apply(TypeFilter.java:57)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.addPFGEdge(DefaultSolver.java:734)
	at pascal.taie.analysis.pta.core.solver.Solver.addPFGEdge(Solver.java:119)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.lambda$processArrayStore$3(DefaultSolver.java:385)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.processArrayStore(DefaultSolver.java:381)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.analyze(DefaultSolver.java:294)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.solve(DefaultSolver.java:238)
	at pascal.taie.analysis.pta.PointerAnalysis.runAnalysis(PointerAnalysis.java:118)
	at pascal.taie.analysis.pta.PointerAnalysis.analyze(PointerAnalysis.java:106)
	at pascal.taie.analysis.pta.PointerAnalysis.analyze(PointerAnalysis.java:63)
	at pascal.taie.analysis.AnalysisManager.runProgramAnalysis(AnalysisManager.java:147)
	at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:120)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$0(AnalysisManager.java:104)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$1(AnalysisManager.java:103)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at pascal.taie.analysis.AnalysisManager.execute(AnalysisManager.java:102)
	at pascal.taie.Main.executePlan(Main.java:143)
	at pascal.taie.Main.lambda$main$0(Main.java:57)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:49)
```

### Tai-e arguments

-ap -cp "snakeyaml-1.21.jar:groovy-2.4.7.jar:spring-expression-4.3.6.RELEASE.jar" -acp "/java-sec-code/target/classes" 
-m org.joychou.Application
-java 8 
-a "pta=only-app:false;implicit-entries:false;taint-config:/Tai-e/src/main/resources/taint-config.yml;action:dump" 
-a "ir-dumper=dump-dir:./sootOutput" 
-a "cg=algorithm:pta;dump:./output/cg.dot" 

### Runtime environment infomation

tai-e commit: https://github.com/pascal-lab/Tai-e/commit/2cfded16f93bb4038ff9322cb892db1c73914a50

**Comment by zhangt2333** [comment]
Here is a temporary workaround for the NPE:

* To modify `pascal.taie.language.classes.ClassHierarchyImpl#isSubclass`
```diff
    @Override
    public boolean isSubclass(JClass superclass, JClass subclass) {
+        // This is a temporary workaround for the NPE
+        try {
            if (superclass.equals(subclass)) {
                return true;
            } else if (superclass == getObjectClass()) {
                return true;
            } /*else if (subclass.isInterface()) {
                return superclass.isInterface() &&
                        isSubinterface(superclass, subclass);
            } else {
                return isSubclass0(superclass, subclass);
            }*/ else {
                return getAllSubclassesOf(superclass).contains(subclass);
            }
+        } catch (NullPointerException e) {
+            logger.warn("NPE in isSubclass, superclass: {}, subclass: {}", 
+                    superclass, subclass);
+        }
+        return false;
    }
```

We are taking a deeper look at this issue and then figure out how to solve it.

**Comment by zhangt2333** [comment]
I can't reproduce this on commit https://github.com/pascal-lab/Tai-e/commit/2cfded16f93bb4038ff9322cb892db1c73914a50, by:
```
-ap
-cp "C:\Users\TTTT\.m2\repository\org\yaml\snakeyaml\1.21\snakeyaml-1.21.jar;C:\Users\TTTT\.m2\repository\org\codehaus\groovy\groovy\2.4.7\groovy-2.4.7.jar;C:\Users\TTTT\.m2\repository\org\springframework\spring-expression\4.3.6.RELEASE\spring-expression-4.3.6.RELEASE.jar"
-acp "../java-sec-code/target/classes"
-m org.joychou.Application
-java 8
-a "pta=only-app:false;implicit-entries:false;taint-config:src/test/resources/pta/taint/taint-config.yml;action:dump"
-a "ir-dumper=dump-dir:./sootOutput"
-a "cg=algorithm:pta;dump:./output/cg.dot"
```

<img src="https://github.com/pascal-lab/Tai-e/assets/35210901/342679ee-97ea-408d-8298-f62aae8e7898" width="400" />



Probably because I'm missing the `taint-config.yml`. Could you provide it?

**Comment by PeteLing** [comment]
> @PeteLing
> 
> I can't reproduce this on commit [2cfded1](https://github.com/pascal-lab/Tai-e/commit/2cfded16f93bb4038ff9322cb892db1c73914a50), by:
> 
> ```
> -ap
> -cp "C:\Users\TTTT\.m2\repository\org\yaml\snakeyaml\1.21\snakeyaml-1.21.jar;C:\Users\TTTT\.m2\repository\org\codehaus\groovy\groovy\2.4.7\groovy-2.4.7.jar;C:\Users\TTTT\.m2\repository\org\springframework\spring-expression\4.3.6.RELEASE\spring-expression-4.3.6.RELEASE.jar"
> -acp "../java-sec-code/target/classes"
> -m org.joychou.Application
> -java 8
> -a "pta=only-app:false;implicit-entries:false;taint-config:src/test/resources/pta/taint/taint-config.yml;action:dump"
> -a "ir-dumper=dump-dir:./sootOutput"
> -a "cg=algorithm:pta;dump:./output/cg.dot"
> ```
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/35210901/242807323-342679ee-97ea-408d-8298-f62aae8e7898.png">
> Could you provide more infomation, e.g., the `taint-config.yml` or an example project or others?

https://github.com/JoyChou93/java-sec-code

**Comment by PeteLing** [comment]
@zhangt2333  the project is https://github.com/JoyChou93/java-sec-code,the taint.config was missed.
It is working if modify the `pascal.taie.language.classes.ClassHierarchyImpl#isSubclass` you mentioned before.

**Comment by zhangt2333** [comment]
Thanks for your feedback. I just wanna take a deeper look at what caused this potential NPE. 
Anyway, if there are no reproducible examples and the above workaround solves your issue, I'd like to close this stale issue.
