### ISSUE TITLE
`OutOfMemoryError` when using 2-limiting context sensitivity

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#41]
### Describe the bug

```java
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at pascal.taie.util.collection.SparseBitSet.getOrCreateBlock(SparseBitSet.java:1017)
	at pascal.taie.util.collection.SparseBitSet.set(SparseBitSet.java:187)
	at pascal.taie.util.collection.GenericBitSet.add(GenericBitSet.java:71)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
	at pascal.taie.util.collection.GenericBitSet.addAll(GenericBitSet.java:103)
	at pascal.taie.util.collection.AbstractHybridSet.upgradeToLargeSet(AbstractHybridSet.java:149)
	at pascal.taie.util.collection.AbstractHybridSet.addAll(AbstractHybridSet.java:175)
	at pascal.taie.analysis.pta.pts.DelegatePointsToSet.addAll(DelegatePointsToSet.java:51)
	at pascal.taie.analysis.pta.core.solver.WorkList.addEntry(WorkList.java:55)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.addPointsTo(DefaultSolver.java:730)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.addPFGEdge(DefaultSolver.java:772)
	at pascal.taie.analysis.pta.core.solver.Solver.addPFGEdge(Solver.java:136)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.processCallEdge(DefaultSolver.java:515)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.analyze(DefaultSolver.java:321)
	at pascal.taie.analysis.pta.core.solver.DefaultSolver.solve(DefaultSolver.java:246)
	at pascal.taie.analysis.pta.PointerAnalysis.runAnalysis(PointerAnalysis.java:118)
	at pascal.taie.analysis.pta.PointerAnalysis.analyze(PointerAnalysis.java:106)
	at pascal.taie.analysis.pta.PointerAnalysis.analyze(PointerAnalysis.java:63)
	at pascal.taie.analysis.AnalysisManager.runProgramAnalysis(AnalysisManager.java:148)
	at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:135)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$0(AnalysisManager.java:104)
	at pascal.taie.analysis.AnalysisManager$$Lambda$251/0x0000000800ece440.get(Unknown Source)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$1(AnalysisManager.java:103)
	at pascal.taie.analysis.AnalysisManager$$Lambda$250/0x0000000800ecdfe8.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at pascal.taie.analysis.AnalysisManager.execute(AnalysisManager.java:102)
	at pascal.taie.Main.executePlan(Main.java:148)
	at pascal.taie.Main.lambda$main$0(Main.java:60)
	at pascal.taie.Main$$Lambda$132/0x0000000800d8d928.run(Unknown Source)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer$$Lambda$133/0x0000000800d8dd80.get(Unknown Source)

Process finished with exit code 1

```

### Tai-e arguments

I specified 126 main methods as entry points and 70 Hadoop jars as input for pointer analysis. When I set the context selector to insensitivity and 1-limiting sensitivity, Tai-e worked normally. However, when I set it to two-limiting sensitivity (whether 2-obj or 2-call), Tai-e threw the `OutOfMemoryError` exception.

### Runtime environment infomation

OS: Ubuntu 18.04
Physical memory: 64GB
The version of Tai-e: latest (https://github.com/pascal-lab/Tai-e/commit/10a633fff58ede7d7f33340a690e8f01159018eb)

Thank you so much!

**Comment by silverbullettt** [comment]
2-obj and 2-call aren't very efficient in terms of time and space. You could try 2-type, which is more scalable than 2-obj and 2-call.

**Comment by anabioticsoul** [comment]
Indeed, the 2-type didn't exhaust the memory. However, it's quite strange that 1-type and 2-type returned the same pointer analysis result.
