### ISSUE TITLE
ClassCastException when doing call graph construction

### ISSUE THREAD

**Issue by zhouxy8525** [pascal-lab/Tai-e#45]
### Describe the bug

Tai-e starts ...
Writing options to output/options.yml
Writing analysis plan to output/tai-e-plan.yml
WorldBuilder starts ...
5798 classes with 54936 methods in the world
WorldBuilder finishes, elapsed time: 11.70s
pta starts ...
[Pointer analysis] elapsed time: 12.79s

#var pointers:                5,0008 (insens) / 5,0008 (sens)
#objects:                     1,1582 (insens) / 1,1582 (sens)
#var points-to:               1524,0102 (insens) / 1524,0102 (sens)
#static field points-to:      4,2060 (sens)
#instance field points-to:    328,1338 (sens)
#array points-to:             34,2971 (sens)
#reachable methods:           7313 (insens) / 7313 (sens)
#call graph edges:            3,8651 (insens) / 3,8651 (sens)

pta finishes, elapsed time: 14.33s
cg starts ...
Call graph has 7313 reachable methods and 38651 edges
Exception in thread "main" java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
        at pascal.taie.config.AnalysisOptions.getString(AnalysisOptions.java:98)
        at pascal.taie.analysis.graph.callgraph.CallGraphBuilder.processOptions(CallGraphBuilder.java:69)
        at pascal.taie.analysis.graph.callgraph.CallGraphBuilder.analyze(CallGraphBuilder.java:57)
        at pascal.taie.analysis.graph.callgraph.CallGraphBuilder.analyze(CallGraphBuilder.java:34)
        at pascal.taie.analysis.AnalysisManager.runProgramAnalysis(AnalysisManager.java:93)
        at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:71)
        at pascal.taie.analysis.AnalysisManager.lambda$execute$0(AnalysisManager.java:60)
        at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
        at pascal.taie.util.Timer.runAndCount(Timer.java:93)
        at pascal.taie.util.Timer.runAndCount(Timer.java:111)
        at pascal.taie.util.Timer.runAndCount(Timer.java:107)
        at pascal.taie.analysis.AnalysisManager.lambda$execute$1(AnalysisManager.java:59)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at pascal.taie.analysis.AnalysisManager.execute(AnalysisManager.java:59)
        at pascal.taie.Main.executePlan(Main.java:142)
        at pascal.taie.Main.lambda$main$0(Main.java:56)
        at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
        at pascal.taie.util.Timer.runAndCount(Timer.java:93)
        at pascal.taie.util.Timer.runAndCount(Timer.java:111)
        at pascal.taie.util.Timer.runAndCount(Timer.java:107)
        at pascal.taie.Main.main(Main.java:48)

### Tai-e arguments

I want to use Tai-e as a tool to generate call graph but witnessed this error when testing it with a simple program

`public class Test{
    public  static void main(String[] args){
        System.out.println("Hello,World!");
    }
}`

The java program only contains one .java file and I compiled and made it into a .jar file as directed by the wiki. My running command is
`java -cp tai-e-all.jar pascal.taie.Main -cp Test.jar -m Test -java 7 -a "cg=algorithm:pta;dump:true;dump-methods:true;dump-call-edges:true"`
Another strange point is that when I execute with the command
`java -cp tai-e-all.jar pascal.taie.Main -cp Test.jar -m Test -java 7 -a "cg=algorithm:pta`
the program worked well

**Tai-e starts ...
Writing options to output/options.yml
Writing analysis plan to output/tai-e-plan.yml
WorldBuilder starts ...
5798 classes with 54936 methods in the world
WorldBuilder finishes, elapsed time: 12.04s
pta starts ...
[Pointer analysis] elapsed time: 11.91s
#var pointers:                5,0008 (insens) / 5,0008 (sens)
#objects:                     1,1582 (insens) / 1,1582 (sens)
#var points-to:               1524,0102 (insens) / 1524,0102 (sens)
#static field points-to:      4,2060 (sens)
#instance field points-to:    328,1338 (sens)
#array points-to:             34,2971 (sens)
#reachable methods:           7313 (insens) / 7313 (sens)
#call graph edges:            3,8651 (insens) / 3,8651 (sens)
pta finishes, elapsed time: 13.30s
cg starts ...
Call graph has 7313 reachable methods and 38651 edges
cg finishes, elapsed time: 0.00s
Tai-e finishes, elapsed time: 25.53s**

but failed once dump configurations were introduced. So I wonder if there is some bug in constructin call graph or my linux environment is not suitable?

### Runtime environment infomation

My environment is on wsl 22.04.2 LTS release and Tai-e is the released version 0.0.3

**Comment by inmaldrerah** [comment]
It seems things have changed quite a bit since v0.0.3. For v0.0.3, the parameters `dump`, `dump-methods`, `dump-call-edges` all require strings to dump files rather than true/false. See [here](https://github.com/pascal-lab/Tai-e/blob/0.0.3/src/main/java/pascal/taie/analysis/graph/callgraph/CallGraphBuilder.java#L69) and [here](https://github.com/pascal-lab/Tai-e/blob/0.0.3/src/main/resources/tai-e-analyses.yml#L29).

So you may choose either to use v0.0.3 and give paths to dump files, or to clone the repository, build tai-e-all.jar yourself and use that with `dump:true`.
