### ISSUE TITLE
NullPointerException occurred during analyzing hadoop

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#5]
Hello everyone, I've met a problem when I tried to analyze *hadoop* components (2.10.2). It did not appear when I analyzed a single component of hadoop, but it came out after adding all dependencies to the `classpath`.
The console log is as follows:
```
Exception in thread "main" java.lang.NullPointerException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:238)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
	at pascal.taie.analysis.AnalysisManager.runMethodAnalysis(AnalysisManager.java:138)
	at pascal.taie.analysis.AnalysisManager.runAnalysis(AnalysisManager.java:75)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$0(AnalysisManager.java:60)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.analysis.AnalysisManager.lambda$execute$1(AnalysisManager.java:59)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at pascal.taie.analysis.AnalysisManager.execute(AnalysisManager.java:59)
	at pascal.taie.Main.executePlan(Main.java:142)
	at pascal.taie.Main.lambda$main$0(Main.java:56)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:48)
	at main.TaieMain.main(TaieMain.java:15)
Caused by: java.lang.NullPointerException: IndexMap does not permit null values
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at pascal.taie.util.collection.IndexMap.put(IndexMap.java:110)
	at pascal.taie.analysis.dataflow.fact.DataflowResult.setInFact(DataflowResult.java:61)
	at pascal.taie.analysis.dataflow.solver.WorkListSolver.initializeForward(WorkListSolver.java:46)
	at pascal.taie.analysis.dataflow.solver.AbstractSolver.initialize(AbstractSolver.java:58)
	at pascal.taie.analysis.dataflow.solver.AbstractSolver.solve(AbstractSolver.java:41)
	at pascal.taie.analysis.dataflow.analysis.AnalysisDriver.analyze(AnalysisDriver.java:48)
	at pascal.taie.analysis.dataflow.analysis.AnalysisDriver.analyze(AnalysisDriver.java:36)
	at pascal.taie.analysis.AnalysisManager.lambda$runMethodAnalysis$3(AnalysisManager.java:140)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
It seems that the problem is caused by the initialization of forward flow analysis. Could you please help me about that, thanks a lot!

**Comment by zhangt2333** [comment]
More information is required to be provided to reproduce and analyze this issue, such as:
* running arguments
* the program you analyze
* ... (additional helpful info)

**Comment by anabioticsoul** [comment]
Thanks for your reply! I've found the problem caused by the `null` value given to the `newBoundaryFact`. But I'm still puzzled by the traversal approach to the analysis in *Tai-e*. Although I've written some test cases including 7 classes, the result of **method** and **class** analysis only includes 5 classes. How could I analyze all the classes in jars? And are there any *docs* available?

**Comment by zhangt2333** [comment]
> How could I analyze all the classes in jars? And are there any *docs* available? 

see `--input-classes` in https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options)

**Comment by anabioticsoul** [comment]
> > How could I analyze all the classes in jars? And are there any _docs_ available?
> 
> see `--input-classes` in https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options)

Adding all classes manually may be a little bit troublesome, but it does solve this problem. Thank you very much!

**Comment by anabioticsoul** [comment]
> > > How could I analyze all the classes in jars? And are there any _docs_ available?
> > 
> > 
> > see `--input-classes` in https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options)
> 
> Adding all classes manually may be a little bit troublesome, but it does solve this problem. Thank you very much!

I found this was a serious problem. Is there any way to add all the classes (which are missed) in the *jar* to the `--input-classes` option? It seems impossible to add manually, and many classes will be missed. I found that some classes were still ignored even when I used `scope ALL` option.

**Comment by zhangt2333** [comment]
> Is there any way to add all the classes (which are missed) in the jar to the --input-classes option?

No support now. Maybe will be supported by our new (but in development) frontend.

A workaround is traversing the classpath, getting all fully-qualified class names of `.class` files (including `.class` files in jar files) and setting to the `--input--classes` argument.

**Comment by anabioticsoul** [comment]
> A workaround is traversing the classpath, getting all fully-qualified class names of `.class` files (including `.class` files in jar files) and setting to the `--input--classes` argument.

Yes, I collected all classes as the input of `--input--classes` by the parsing all the jars through `java.util.jar.JarFile`. It successfully reduced a large number of false positives, which can be an alternative choice at present. Thank you very much!
