### ISSUE TITLE
Bug in taint-config

### ISSUE THREAD

**Issue by Peteling** [pascal-lab/Tai-e#51]
### Describe the bug

if you provide a sink rules like 
```
sinks:
  - { method: "<SourceSink: void sink(java.lang.String,java.lang.String)>", index: 0 }
  - { method: "<SourceSink: void sink(java.lang.String,java.lang.String)>", index: 1 }
```
it will occur errors
```
Exception in thread "main" java.lang.IllegalStateException: Duplicate key <SourceSink: void sink(java.lang.String,java.lang.String)> (attempted merging values <SourceSink: void sink(java.lang.String,java.lang.String)>/0 and <SourceSink: void sink(java.lang.String,java.lang.String)>/1)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at pascal.taie.analysis.pta.plugin.taint.SinkHandler.collectTaintFlows(SinkHandler.java:73)
	at pascal.taie.analysis.pta.plugin.taint.TaintAnalysis.onFinish(TaintAnalysis.java:97)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

### Tai-e arguments

```
-ap -java 8 
-acp "/target/classes" 
-m "test" 
--output-dir "/Tai-e/output"
-a "pta=cs:ci;only-app:false;implicit-entries:false;taint-config:taint-config.yml;dump:true" 
```

**Comment by zhangt2333** [comment]
Try the following hot fix, and then please tell me if it solve your issue:

https://github.com/pascal-lab/Tai-e/blob/af0f6da76dd13d85a75f9dafae462c4250809d89/src/main/java/pascal/taie/analysis/pta/plugin/taint/SinkHandler.java#L72-L82

```diff
+import pascal.taie.util.collection.MultiMap;
+import pascal.taie.util.collection.MultiMapCollector;
+import java.util.function.Function;
...
-            Map<JMethod, Sink> sinkMap = sinks.stream()
-                    .collect(Collectors.toMap(Sink::method, s -> s));
+            MultiMap<JMethod, Sink> sinkMap = sinks.stream()
+                    .collect(MultiMapCollector.get(Sink::method, Function.identity()));
            // scan all reachable call sites to search sink calls
            result.getCallGraph()
                    .reachableMethods()
                    .filter(m -> !m.isAbstract())
                    .flatMap(m -> m.getIR().invokes(false))
                    .forEach(callSite -> {
                        JMethod callee = callSite.getMethodRef().resolveNullable();
-                        Sink sink = sinkMap.get(callee);
-                        if (sink != null) {
+                        for (Sink sink : sinkMap.get(callee)) {
```

**Comment by Peteling** [comment]
It seems works! 
But in the following code, the `callee` maybe null. 
```
for (Sink sink : sinkMap.get(callee))
```

**Comment by zhangt2333** [comment]
Oh, I just remember that `HashMap` can accpet `null` key and forget to check ours.

Updated above.

**Comment by zhangt2333** [comment]
Fixed in https://github.com/pascal-lab/Tai-e/commit/24caba62a537184a85a5f768726783cbeafb940e.
