### ISSUE TITLE
soot error when using --input-classes

### ISSUE THREAD

**Issue by Peteling** [pascal-lab/Tai-e#52]
### Describe the bug

when using --input-classes, it will occur the Runtime error 
```
Exception in thread "main" java.lang.RuntimeException: Attempt to create RefType containing a / --> tomcat-embed-core-8.5.85.jar
	at soot.RefType.<init>(RefType.java:57)
	at soot.Scene.lambda$getOrAddRefType$1(Scene.java:2232)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at soot.Scene.getOrAddRefType(Scene.java:2232)
	at soot.RefType.v(RefType.java:85)
	at soot.SootClass.initializeRefType(SootClass.java:158)
	at soot.SootClass.<init>(SootClass.java:140)
	at soot.SootClass.<init>(SootClass.java:127)
	at soot.SootResolver.makeClassRef(SootResolver.java:138)
	at soot.SootResolver.resolveClass(SootResolver.java:153)
	at soot.Scene.loadClass(Scene.java:1016)
	at soot.Scene.loadClassAndSupport(Scene.java:1003)
	at soot.Scene.loadNecessaryClass(Scene.java:1944)
	at soot.Scene.loadNecessaryClasses(Scene.java:1956)
	at soot.Main.run(Main.java:240)
	at pascal.taie.frontend.soot.SootWorldBuilder.runSoot(SootWorldBuilder.java:256)
	at pascal.taie.frontend.soot.SootWorldBuilder.build(SootWorldBuilder.java:84)
	at pascal.taie.Main.lambda$buildWorld$3(Main.java:132)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.buildWorld(Main.java:124)
	at pascal.taie.Main.lambda$main$0(Main.java:60)

```
I think that is a bug in Soot, but I just want to know that someone has the idea which can handle the situation.I also searched in soot issues and did not find any solutions.

### Tai-e arguments

--input-classes="/tmp/tomcat-embed-core-8.5.85.jar"

**Comment by zhangt2333** [comment]
The <inputClass> should follow the format of fully-qualified name in Java, e.g., org.package.MyClass.

**Comment by Peteling** [comment]
Thanks~ I should see the document carefully~ 
In this case, it seems I should us `-cp` add the third-party jar and use `--input-classes`
