### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by testmigrator** [pascal-lab/Tai-e#53]
### Describe the bug

# background
I completed the configuration of tai-e in idea according to the tutorial, and then I tried to run the test case that came with tai-e, but a NPE was reported

I noticed that there was an issue #13  report on the same problem, but the solution was not very detailed. I tried all kinds of solutions but it didn't work

I would like to ask how to solve this problem

# error 
when I run any test case in tai-e：

```java
WorldBuilder starts ...
java.lang.NullPointerException: Cannot invoke "soot.JastAddJ.ClassDecl.localMethodsSignature(String)" because the return value of "soot.JastAddJ.ClassDecl.superclass()" is null
	at soot.JastAddJ.ClassDecl.ancestorMethods_compute(ClassDecl.java:1155)
	at soot.JastAddJ.ClassDecl.ancestorMethods(ClassDecl.java:1145)
	at soot.JastAddJ.TypeDecl.refined_TypeHierarchyCheck_TypeDecl_typeCheck(TypeDecl.java:704)
	at soot.JastAddJ.TypeDecl.typeCheck(TypeDecl.java:1640)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1284)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.CompilationUnit.errorCheck(CompilationUnit.java:178)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:67)
	at soot.JavaClassSource.resolve(JavaClassSource.java:63)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:274)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:243)
	at soot.SootResolver.bringToSignatures(SootResolver.java:313)
	at soot.SootResolver.bringToBodies(SootResolver.java:353)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:190)
	at soot.SootResolver.resolveClass(SootResolver.java:155)
	at soot.Scene.loadClass(Scene.java:1016)
	at soot.Scene.loadClassAndSupport(Scene.java:1003)
	at soot.Scene.loadNecessaryClass(Scene.java:1944)
	at soot.Scene.loadNecessaryClasses(Scene.java:1956)
	at soot.Main.run(Main.java:240)
	at pascal.taie.frontend.soot.SootWorldBuilder.runSoot(SootWorldBuilder.java:252)
```

### Tai-e arguments

I didn't set my own parameters and ran the test case that came with tai-e

### Runtime environment infomation
tai-e: latest version 0.0.3 on Jul 31, 2022
jdk: corretto-17.0.8

**Comment by zhangt2333** [comment]
```shell
git clone https://github.com/pascal-lab/Tai-e
cd Tai-e
git submodule update --init --recursive
./gradlew testTaieTestSuite                        # ensure 'java -version' outputs 'openjdk version "17...'
```

**Comment by testmigrator** [comment]
> ```shell
> git clone https://github.com/pascal-lab/Tai-e
> cd Tai-e
> git submodule update --init --recursive
> ./gradlew testTaieTestSuite                        # ensure 'java -version' outputs 'openjdk version "17...'
> ```

Thanks. Looks like it worked
