### ISSUE TITLE
Make pointer analysis only analyze the specified packages/classes/methods

### ISSUE THREAD

**Issue by houanran-hzh** [pascal-lab/Tai-e#76]
### Description

我尝试用tai-e去分析安卓源码的框架层，但是需要的依赖过多，有一些甚至是不必要的，在tai-e框架 中，是否有办法指定分析边界？比如分析到了某个类就默认按我所写的逻辑执行？报错信息如下：
Exception in thread "main" java.lang.RuntimeException: couldn't find class: dalvik.annotation.optimization.FastNative (are your class path and class name given properly?)
        at pascal.taie.frontend.soot.SootWorldBuilder.runSoot(SootWorldBuilder.java:259)
        at pascal.taie.frontend.soot.SootWorldBuilder.build(SootWorldBuilder.java:84)
        at pascal.taie.Main.lambda$buildWorld$3(Main.java:132)
        at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
        at pascal.taie.util.Timer.runAndCount(Timer.java:93)
        at pascal.taie.util.Timer.runAndCount(Timer.java:111)
        at pascal.taie.util.Timer.runAndCount(Timer.java:107)
        at pascal.taie.Main.buildWorld(Main.java:124)
        at pascal.taie.Main.lambda$main$0(Main.java:59)
        at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
        at pascal.taie.util.Timer.runAndCount(Timer.java:93)
        at pascal.taie.util.Timer.runAndCount(Timer.java:111)
        at pascal.taie.util.Timer.runAndCount(Timer.java:107)
        at pascal.taie.Main.main(Main.java:51)
在此之前我已经用cp命令导入了framework.jar的内容。

**Comment by zhangt2333** [comment]
Thanks for writing this issue in Chinese, it makes it very easy for a few of us developers to read. However, Tai-e is a project with an international focus, and we aim to keep our community discussions in as widely accessible a language as possible, which is English. This helps us share our open-source progress with interested individuals from all over the world. Kindly consider using English for communication in the future. We appreciate your understanding. Thank you.

---

You can modify the following methods so that pointer analysis ignores some packages or classes or methods:

https://github.com/pascal-lab/Tai-e/blob/d45ff7015d043bf73d0a2a52aab1e2836eaa97e6/src/main/java/pascal/taie/analysis/pta/core/solver/DefaultSolver.java#L527

Besides, you can leave classes you don't need to analyse out of the classpath while enabling the option `Allow phantom references (-ap, --allow-phantom)`. (https://tai-e.pascal-lab.net/docs/current/reference/en/command-line-options.html)

**Comment by fangyuan00** [comment]
@zhangt2333 
Hi, I have the issue about setting the option `Allow phantom references (-ap, --allow-phantom)`.
I use Tai-e-0.5.1-snapshot as my maven dependency, and my code is as follows.
```
pascal.taie.Main.buildWorld("-cp", $JARPATH, 
        "-acp", $MYCLASSPATH, 
        "-java", "8", 
        "--allow-phantom", "true", 
        "-a", "pta=cs:ci;only-app:true;dump-ci:true;dump-yaml:true", "-scope", "REACHABLE");
```
I have tried various forms of 'true' and 'false', including 'True', 'TRUE', 'true', true, and so on. However, the program still throws an error. The error message is as follows.
```
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unmatched argument at index 7: 'true'
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13604)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13556)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13501)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13396)
	at picocli.CommandLine.parse(CommandLine.java:1534)
	at picocli.CommandLine.populateCommand(CommandLine.java:1476)
	at pascal.taie.config.Options.parse(Options.java:296)
	at pascal.taie.Main.buildWorld(Main.java:116)
	at org.example.Main.main(Main.java:71)
```
My environment is as follows.
```
maven dependency: Tai-e-0.5.1-snapshot
system: MacOS
compiler: IDEA
```
I am not sure if the program encountered an error due to my usage error, but when I removed the line with "--allow-phantom", "true", the code could run normally. However, without ignoring classes, it would still result in an error. The information is as follows:
```
Output directory: $DIR/output
Writing options to $DIR/output/options.yml
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Writing log to $DIR/output/tai-e.log
Writing analysis plan to $DIR/output/tai-e-plan.yml
WorldBuilder starts ...
Scanning $MYCLASSPATH ... 16 classes
Exception in thread "main" java.lang.RuntimeException: couldn't find class: com.github.gumtreediff.actions.TreeClassifier (are your class path and class name given properly?)
	at pascal.taie.frontend.soot.SootWorldBuilder.runSoot(SootWorldBuilder.java:259)
	at pascal.taie.frontend.soot.SootWorldBuilder.build(SootWorldBuilder.java:84)
	at pascal.taie.Main.lambda$buildWorld$3(Main.java:132)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.buildWorld(Main.java:124)
	at pascal.taie.Main.buildWorld(Main.java:119)
	at org.example.Main.main(Main.java:71)
```
I am a beginner in Tai-e and would greatly appreciate your assistance. Thank you.

**Comment by zhangt2333** [comment]
@fangyuan00 Thank you for providing detailed reproduction steps.

---

> I have tried various forms of 'true' and 'false', including 'True', 'TRUE', 'true', true, and so on. However, the program still throws an error. The error message is as follows.

Just use `--allow-phantom`, No need to follow any values afterwards.
