### ISSUE TITLE
 java.lang.RuntimeException: Attempt to create RefType containing ...

### ISSUE THREAD

**Issue by SEC-fsq** [pascal-lab/Tai-e#84]
### Description

Tai-e starts ...
Output directory: /Users/didi/Downloads/taiedemo/output
Writing options to /Users/didi/Downloads/taiedemo/output/options.yml
Writing log to /Users/didi/Downloads/taiedemo/output/tai-e.log
Writing analysis plan to /Users/didi/Downloads/taiedemo/output/tai-e-plan.yml
WorldBuilder starts ...
Exception in thread "main" java.lang.RuntimeException: Attempt to create RefType containing a / --> /Users/didi/Downloads/taiedemo/target/classes
	at soot.RefType.<init>(RefType.java:57)
	at soot.Scene.lambda$getOrAddRefType$1(Scene.java:2232)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at soot.Scene.getOrAddRefType(Scene.java:2232)
	at soot.RefType.v(RefType.java:85)
	at soot.SootClass.initializeRefType(SootClass.java:158)
	at soot.SootClass.<init>(SootClass.java:140)
	at soot.SootClass.<init>(SootClass.java:127)
	at soot.SootResolver.makeClassRef(SootResolver.java:138)
	at soot.SootResolver.resolveClass(SootResolver.java:153)
	at soot.Scene.loadClass(Scene.java:1016)
	at soot.Scene.loadClassAndSupport(Scene.java:1003)
	at soot.Scene.loadNecessaryClass(Scene.java:1944)
	at soot.Scene.loadNecessaryClasses(Scene.java:1956)
	at soot.Main.run(Main.java:240)
	at pascal.taie.frontend.soot.SootWorldBuilder.runSoot(SootWorldBuilder.java:256)
	at pascal.taie.frontend.soot.SootWorldBuilder.build(SootWorldBuilder.java:84)
	at pascal.taie.Main.lambda$buildWorld$3(Main.java:132)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.buildWorld(Main.java:124)
	at pascal.taie.Main.lambda$main$0(Main.java:59)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:51)
	at org.example.Main.main(Main.java:17)

**Comment by zhangt2333** [comment]
This is your third issue which is still using Chinese. If this happens again, we will disable your account from interacting with our repository! 

In addition, you don't need to create multiple issues. Just add information to the previous issue.

We appreciate your understanding.

Thanks for writing this issue in Chinese, it makes it very easy for a few of us developers to read. However, Tai-e is a project with an international focus, and we aim to keep our community discussions in as widely accessible a language as possible, which is English. This helps us share our open-source progress with interested individuals from all over the world. Kindly consider using English for communication in the future. We appreciate your understanding. Thank you.

--- 

> Exception in thread "main" java.lang.RuntimeException: Attempt to create RefType containing a / --> /Users/didi/Downloads/taiedemo/target/classes

This seems to be a front-end related issue. Try to enable the option Allow phantom references (`-ap`, `--allow-phantom`). (https://tai-e.pascal-lab.net/docs/current/reference/en/command-line-options.html)

More information is required to answer your question, e.g.,

- what have you done to try to solve this problem?
- how can we reproduce the same problem as you to help?
...

Then we know how we can help you.
